version: 0.2

phases:
  install:
    runtime-versions:
      php: 7-alpine
build:
  commands:
    - php -v

artifacts:
  files:
    - '**/*'
  base-directory: 'AndrewDass1/Hemia-Team2_Kura_Final_Project'

