version: 2
jobs:
  build:
    working_directory: ~/.circleci
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
