version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: 'circleci/python:3.10.1'
        auth:
          username: andrewdass
          password: 'DockerToken'  # context / project UI env-var reference
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: database.cw720ufh2k84.us-east-1.rds.amazonaws.com
      - image: circleci/postgres:9.6.2

    steps:
      - checkout
      - run: pip install --upgrade -r requirements.txt
      - run: echo "this is the build job"
        
  test:
    docker:
      - image: 'andrewdass/hemia-1.0'
        auth:
          username: andrewdass
          password: 'DockerToken' # context / project UI env-var reference
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: database
    steps:
      - checkout
      - run: echo "this is the test job"
    
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
