version: 2.1

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
          context:
            - org-global
            - keys
      - test:
          context:
            - org-global
            - keys
      - deploy:
          context:
            - org-global
            - keys

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-stretch-node-browsers
        environment:
          MYSQL_ROOT_PASSWORD: Password
          MYSQL_HOST: Host
      - image: andrewdass/hemia-1.0
        auth:
          username: andrewdass
          password: $DOCKERTOKEN

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    steps:
      - checkout
      - run: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
      - run: pip install --upgrade -r requirements.txt
      - run: sudo apt-get update
      - run: pip3 install install awsebcli --upgrade
      - run:
          name: Database
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install mysql-client
            sudo apt-get -y install mysql-server
      - run:
          name: PHP
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install intl
            sudo docker-php-ext-install pdo_mysql
      - run:
          name: Fix MySQL socket config
          command: |
            sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"
      - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
      - run:
          name: Create non-admin user
          command: |
            sudo mysql -u root -e "CREATE user myuser IDENTIFIED BY 'password';"
  
  
  test:
    docker:
      - image: andrewdass/hemia-1.0
        auth:
          username: andrewdass
          password: $DOCKERTOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Testing the application with pytest"
      # - run: python -m pytest
  
  
  deploy:
    docker:
      - image: andrewdass/hemia-1.0
        auth:
          username: andrewdass
          password: $DOCKERTOKEN  # context / project UI env-var reference  
    steps:
      - checkout
      - run: echo "Successful deployment"


