version: 2.1

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
          context:
            - org-global
            - keys

orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-s3: circleci/aws-s3@3.0 

  aws-rds: ware2go/aws-rds@0.2.123


jobs:
  build:
    docker:
      - image: circleci/mysql:latest
        auth:
          username: andrewdass
          password: DOCKERTOKEN # context / project UI env-var reference
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
 
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"
