version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0
 
# Define the jobs we want to run for this project

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        auth:
          username: andrewdass
          password: 4719e342-a846-4ca5-9357-2befc754b105  # context / project UI env-var reference
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: database.cw720ufh2k84.us-east-1.rds.amazonaws.com
      - image: circleci/postgres:9.6.2

    steps:
      - checkout
      - run: pip install --upgrade -r requirements.txt
      - run: echo "this is the build job"
        
  test:
    docker:
      - image: circleci/python:3.7.4
        auth:
          username: andrewdass
          password: 4719e342-a846-4ca5-9357-2befc754b105  # context / project UI env-var reference
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: database
    steps:
      - checkout
      - run: echo "this is the test job"
    
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
