version: 2.1

workflows:
  build_and_test_and_deploy:
    jobs:
      - build:
          context: 
            - org-global
            - keys
      # - test:
      #     context:
      #       - org-global
      #       - keys
      # - deploy: 
      #     context: 
      #       - org-global
      #       - keys

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:

  build:
    docker:
      - image: andrewdass/hemiaphp
        auth: 
          username: andrewdass
          password: $DOCKERTOKEN

    steps:
      - checkout

      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL  
          repo: AWS_REPO
          tag: TAG
      
      - aws-ecs/run-task:
          awsvpc: false
          cluster: test2
          launch-type: FARGATE
          task-definition: testdef
  # test:
  #   docker:
  #     - image:
  #       auth:  

  # deploy:
  #   docker:
  #     - image: 
  #       auth: 


