version: 2
jobs:
  build:
    working_directory: ~/.circleci
    docker:
      - image: circleci/python:3.9  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: pip install -i requirements.txt
